apiVersion: v1
kind: Service
metadata:
  name: react-k8s-test-service
  labels:
    app: react-k8s-test
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32001
  selector:
    app: react-k8s-test